### ISSUE TITLE
Error with JUnit

### ISSUE THREAD

**Issue by daniel-rocha** [Apress/pro-spring-5#13] opened 2019-04-11 13:08 UTC
Could not find method useJUnitPlatform() for arguments [] on task ':chapter13:junit5-test:test' of type org.gradle.api.tasks.testing.Test.

This is the very first setup with IntelliJ.

**Comment by iuliana** [comment] 2019-04-11 21:22
Hi, 

How did you get that error? Did you just execute the test task from the Gradle project view?  Or from the command line? 

Did you upgrade the JUnit version (later version have serious API changes are require different Gradle setup)? Are you using Gradle 4.0?  (project is limited to this version because of a plugin it is using)

Give me some more details here please because, building the project with `gradle build -x test` works, and executing the tests directly in Intellij works too (proof: https://i.imgur.com/AXC7xkm.png ). 

And I do not want to be that person that says 'it works on my machine' , but unfortunately it does, so a little bit of extra help is needed. 

Waiting to hear from you! 
Cheers!

**Comment by daniel-rocha** [comment] 2019-04-13 13:29
Hello,

I'm using Gradle 4.0, yes. It was simply getting IntelliJ ultimate, File / Open / Project and import wizard started. 

I've simply imported the root folder into IntelliJ, and it began syncing the project, downloading libraries, and building. It failed only when it got to Chapter 13. I have moved to Maven (may make a PR later to your repo with the pom.xml files for folks using Maven) for the time being, but I will retry and see what the results are.

I think you can close this issue and I'll reopen once I try again. 

Thanks!

**Comment by iuliana** [comment] 2019-04-14 02:39
Hi, 

I will try to re-clone the repo tomorrow and re-import it in IntelliJ again. Maybe I'll be able to replicate the issue. 
I do not feel comfortable closing the issue, because somebody else might get it as well. So I'd rather give it one more try.

Cheers, 
Iuliana Cosmina

**Comment by iuliana** [comment] 2019-04-14 12:00
Managed to reproduce it. Working on providing a fix now. Thank you!

**Comment by iuliana** [comment] 2019-04-14 21:36
Hello Daniel, 
I've found the cause and it's gonna be difficult to fix. No idea how this issue escaped me so far.  Probably IntelliJ keeps old class files, so builds in my old workspace work fine.

Project is limited to 4.0 because of the `aspectj-plugin` that uses a Gradle function that was removed in 4.6. I was unable so far to get rid of this plugin so far, but I'm still trying. ;)

But in 4.6 the `useJUnitPlatform()` was added. So if I want both modules to work I need to replace the `aspectj-plugin`. 

Good part is that I currently have a work-around for you if you want to use the Gradle build. In the `settings.gradle` file, comment the line containing`include 'chapter13:junit5-test'`.  When you get to chapter 13, upgrade Gradle to 4.6 and remove the comment. If it doesn't build just comment the line containing `include 'chapter05:aspectj-aspects'` in `settings.gradle`. 

I'll push a solution as soon as I have one.

**Comment by iuliana** [comment] 2019-04-14 23:47
I've taken out the problematic project and added an independent configuration with Gradle 4.0 for it. 
Support for AspectJ files will not be continues as a topic in the next revisions of the book, so the project will be dropped altogether in the next revision. 

By taking out the project that was blocking the upgrade of Gradle, now the project can be build with Gradle 5.x.

I hope this solution is acceptable.

**Comment by daniel-rocha** [comment] 2019-04-15 13:10
That works. I'm mostly working with Maven, but have also tried the fix above and it worked well. Thanks for taking a look at it!

**Closed** 2019-04-15 18:53 UTC
